[project]
authors = ["Erik Tollerud <erik.tollerud@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "python_experimentation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
moderngl = ">=5.11.1,<6"
numpy = "<2"
moderngl-window = ">=2.4.1,<3"

[pypi-dependencies]
pyglm = ">=2.7.2, <3"
